import type { Metadata } from "next";
import { geistSans, geistMono, figtree } from "@/lib/fonts";
import { NextIntlClientProvider } from 'next-intl';
import "./globals.css";
import Footer from "@components/Footer";
import NavigationBar from '@components/NavigationBar';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} ${figtree.variable} antialiased`}>
        <NextIntlClientProvider locale={locale}>
          <NavigationBar />
          {children}
          <Footer/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
