import { NextIntlClientProvider } from 'next-intl';
import "./global.css";
import Footer from "@components/Footer";
import NavigationBar from '@components/NavigationBar';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className="geistSans variable geistMono variable figtree variable antialiased">
        <NextIntlClientProvider locale={locale}>
          <NavigationBar />
          {children}
          <Footer/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

