import { NextIntlClientProvider } from 'next-intl';
import Footer from "@/components/UI/Footer";
import NavigationBar from '@/components/UI/NavigationBar';
import {getMessages} from 'next-intl/server';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
    const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className="geistSans variable geistMono variable figtree variable antialiased">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <NavigationBar />
          {children}
          <Footer/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

